#!/usr/bin/env bash

set -euo pipefail

# Step 1: Convert PDF to images.

extracted_images="./work/extracted_images"
rm -rf "$extracted_images"
mkdir -p "$extracted_images"

# Check if an input file was provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <PDF file>"
    exit 1
fi

input_pdf="$1"

echo "[STEP 1] Converting PDF to images"
total_pages="$(pdfinfo "$input_pdf" | grep Pages | awk '{print $2}')"
echo "Counted $total_pages total pages"
parallel --quote --bar -j 16 pdftoppm -png -f "{}" -l "{}" -r 300 "$input_pdf" "$extracted_images/page" ::: $(seq 1 "$total_pages")
