#!/usr/bin/env bash

set -euo pipefail

# Step 1: Convert PDF to images.

extracted_images="./work/extracted_images"
mkdir -p "$extracted_images"

# Check if an input file was provided
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <PDF file>"
    exit 1
fi

input_pdf="$1"

echo "Converting PDF to images..."
pdftoppm -progress -r 300 "$input_pdf" "$extracted_images/page" -png
