#!/usr/bin/env bash

set -euo pipefail

# Step 2: Use textcleaner to clean the images and create PDFs.

extracted_images="./work/extracted_images"
cleaned_images="./work/cleaned_images"
mkdir -p "$cleaned_images"

for i in "$extracted_images"/*; do
    echo "Cleaning page $i"
    ./textcleaner -g -e stretch -f 25 -o 10 -u -s 1 "$i" "$cleaned_images/$(basename "$i")"
done
