#!/usr/bin/env bash

set -euo pipefail

# Step 2: Use textcleaner to clean the images and create PDFs.

extracted_images="./work/extracted_images"
cleaned_images="./work/cleaned_images"
mkdir -p "$cleaned_images"

echo "[STEP 2] Cleaning pages"
parallel --bar -j 16 ./textcleaner -g -e stretch -f 25 -o 10 -u -s 1 "{}" "$cleaned_images/{/}" ::: "$extracted_images"/*.png
