#!/usr/bin/env bash

set -euo pipefail

# Step 3: Resize all images to the same size.

cleaned_images="./work/cleaned_images"
resized_images="./work/resized_images"
mkdir -p "$resized_images"

echo "[STEP 3] Resizing pages"
cp "$cleaned_images"/* "$resized_images"
parallel --bar -j 16 mogrify -resize 1590x2557 -background white -gravity center -extent 1590x2557 ::: "$resized_images"/*.png
