#!/usr/bin/env bash

set -euo pipefail

# Step 4: OCR all images with tesseract.

resized_images="./work/resized_images"
ocr_images="./work/ocr_images"
mkdir -p "$ocr_images"

cp "$resized_images"/* "$ocr_images"
for img in "$ocr_images"/*.png; do
  echo "OCRing $img"
  tesseract "$img" "${img%.png}" pdf
done
