#!/usr/bin/env bash

set -euo pipefail

# Step 4: OCR all images with tesseract.

resized_images="./work/resized_images"
ocr_images="./work/ocr_images"
mkdir -p "$ocr_images"

echo "[STEP 4] OCRing pages"
cp "$resized_images"/* "$ocr_images"
parallel --bar -j 4 tesseract "{}" "{}" pdf ::: "$ocr_images"/*.png
