#!/usr/bin/env bash

set -euo pipefail

# Step 4: OCR all images with tesseract.

quantized_images="./work/quantized_images"
ocr_images="./work/ocr_images"
mkdir -p "$ocr_images"

echo "[STEP 5] OCRing pages"
cp "$quantized_images"/* "$ocr_images"
parallel --bar -j 4 tesseract "{}" "{}" pdf ::: "$ocr_images"/*.png
