#!/usr/bin/env bash

set -euo pipefail

# Check if an input file was provided
if [ "$#" -eq 0 ]; then
    echo "Usage: $0 <PDF file> [<resume from step>]"
    exit 1
fi

input_pdf="$1"

# Set the starting step based on second argument; otherwise default 1.
starting_step="${2:-1}"

[ "$starting_step" -eq 1 ] && ./reset
[ "$starting_step" -lt 2 ] && ./1_extract_images "$input_pdf"
[ "$starting_step" -lt 3 ] && ./2_clean_images
[ "$starting_step" -lt 4 ] && ./3_resize_images
[ "$starting_step" -lt 5 ] && ./4_quantize_images
# Run ocrmypdf by hand afterwards... OCR takes too long when we are experimenting with the clean quality.
# [ "$starting_step" -lt 6 ] && ./5_ocr_images
[ "$starting_step" -lt 7 ] && ./6_merge_images
